onboarding = false

[theme]
name = "dracula"
auto_switch = false

[ui]
status_indicators = "symbols"
show_agent_labels_on_pane_borders = true
prompt_new_workspace_name = true
agent_panel_sort = "spaces"

[terminal]
new_cwd = "~/dev/sandbox"

[keys]
prefix = "ctrl+space"

[[keys.command]]
key = "prefix+t"
type = "plugin_action"
command = "herdr-navigator.open"
description = "jump to anything"

[[keys.command]]
key = "prefix+shift+b"
type = "shell"
command = '"$HERDR_BIN_PATH" pane move "$HERDR_ACTIVE_PANE_ID" --new-tab --focus'
description = "break pane into tab"
